# This is a basic workflow to help you get started with Actions

name: TF Mirror

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Checkout
        uses: actions/checkout@main
      - name: Package
        working-directory: ./tf-files
        run: |
          curl -fs https://releases.hashicorp.com/terraform/1.0.11/terraform_1.0.11_linux_amd64.zip -o ./tf.zip 
          unzip tf.zip
          rm tf.zip
          chmod +x terraform
          mkdir ./terraform-provider-mirror
          ls -al 
          ./terraform providers mirror ./terraform-provider-mirror
          zip -r tf-provider.zip ./terraform-provider-mirror
          base64 tf-provider.zip > tf-provider.zip.b64
      - name: Clean releases
        uses: ame-yu/action-delete-latest-release@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: latest
          tag_name: latest
          files: ./tf-files/tf-provider.zip.b64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
