# This is a basic workflow to help you get started with Actions

name: TF Mirror

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        working-directory: tf-files
        run: |
          curl https://releases.hashicorp.com/terraform/0.14.7/terraform_0.14.7_linux_amd64.zip -o ./tf.zip 
          unzip tf.zip
          rm tf.zip
          chmod +x terraform
          mkdir ./local-provider-mirror
          ls -al 
          ./terraform providers mirror ./local-provider-mirror
          zip tf-provider.zip ./local-provider-mirror
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: tf-mirror
          path: tf-provider.zip
          retention-days: 25
