# This is a basic workflow to help you get started with Actions

name: TF Mirror

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - uses: actions/checkout@main
      - name: Run a multi-line script
        working-directory: ./tf-files
        run: |
          curl https://releases.hashicorp.com/terraform/0.14.7/terraform_0.14.7_linux_amd64.zip -o ./tf.zip 
          unzip tf.zip
          rm tf.zip
          chmod +x terraform
          mkdir ./local-provider-mirror
          ls -al 
          ./terraform providers mirror ./local-provider-mirror
          zip -r tf-provider.zip ./local-provider-mirror
          base64 tf-provider.zip > tf-provider.zip.b64
#      - name: 'Upload Artifact'
#        uses: actions/upload-artifact@v2
#        with:
#          name: tf-mirror
#          path: ./tf-files/tf-provider.zip
#          retention-days: 25
      - name: Commit files
        run: |
          git config --local user.email "noreplay+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add ./tf-files/tf-provider.zip*
          git commit -m "Add TF Zip" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: zip
          force: true
